### ISSUE TITLE
Bug bundle

### ISSUE THREAD

**Issue by iKatt** [TakosThings/Metro-for-Discord#29] opened 2018-05-10 14:20 UTC
1: Plugins are too close to the now, different color settings options on the left.
![image](https://user-images.githubusercontent.com/10321978/39874171-655d0ec2-54b0-11e8-90b0-40a07951623a.png)
2: Mentioning someone on an image shows a white mention list, and breaks through some elements (at the top).
![image](https://user-images.githubusercontent.com/10321978/39874207-81bc3a3e-54b0-11e8-85cb-e5f039b0ff9e.png)
3: Member search box is still Discord gray.
![image](https://user-images.githubusercontent.com/10321978/39874232-98bb7f74-54b0-11e8-9596-e42f40cb88f9.png)
4: Right clicking some users on the member panel makes the popup element too high (clips with the Discord window). Resizing the Discord window does not fix this.
![image](https://user-images.githubusercontent.com/10321978/39874310-c7b4b638-54b0-11e8-9304-8d20cf5d0531.png)
5: Scrolling through the emoji menu sometimes renders the mouse unable to click an emoji, this can be temporarily fixed by scrolling up or down. (Cannot screencap this).

**Comment by TakosThings** [comment] 2018-05-10 15:19
### Checklist
- [ ] BetterDiscord plugins, themes settings
- [ ] Upload modal mention list
- [ ] Server settings users list search box
- [ ] Context menu can clip under windows titlebar
- [x] Emoji picker doesn't accept user interactions at random intervals (see below)

---
The emoji picker bug is a long standing issue caused by lazy loading. A 'workaround' is just to scroll to a different position.

**Comment by iKatt** [comment] 2018-05-11 02:26
@TakosThings 
6: Double digit timestamps (10, 11, 12) are too close to the left of the screen, making it hard to copy and paste chat logs. 
![image](https://user-images.githubusercontent.com/10321978/39903434-8e97fe30-5516-11e8-8ee8-da58ef83a5c5.png)

**Comment by TakosThings** [comment] 2018-05-12 04:38
Other commit references I forgot to add:

**Comment by TakosThings** [comment] 2018-05-12 05:14
Marking context menu issue as wontfix

**Closed** 2018-05-12 05:14 UTC
Labels: BetterDiscord, Bug
