### ISSUE TITLE
probem with dms

### ISSUE THREAD

**Issue by andrew071117** [TakosThings/Metro-for-Discord#238] opened 2021-05-26 23:18 UTC
I see overlapiing icon in it
![image](https://user-images.githubusercontent.com/81406482/119743111-2826dd80-be57-11eb-9786-d433d2d4f491.png)

**Comment by TakosThings** [comment] 2021-05-28 11:25
Duplicate of #230

**Closed by TakosThings** 2021-05-28 11:25 UTC
Labels: duplicate
