### ISSUE TITLE
Profile Modal Bugs

### ISSUE THREAD

**Issue by silent** [TakosThings/Metro-for-Discord#104] opened 2019-07-22 04:27 UTC
**Describe the bug**
When clicking on different peoples names in the chat their profile will pop up but on some users, they will pop up in the middle of the screen or even extend into the title bar instead of being on the right side. This doesn't happen for every user I click on but it's a weird glitch nonetheless. 

**Screenshots**
![image](https://user-images.githubusercontent.com/36117192/61606263-0501c600-ac0f-11e9-89e8-d5042a7cfea8.png)
![image](https://user-images.githubusercontent.com/36117192/61606264-07642000-ac0f-11e9-9b64-f2e6a5882137.png)

**Comment by TakosThings** [comment] 2019-08-09 04:22
Closing - Cannot reproduce, duplicate of #93

**Closed by TakosThings** 2019-08-09 04:22 UTC
Labels: Duplicate
