### ISSUE TITLE
Profile Picture off centered 

### ISSUE THREAD

**Issue by silent** [TakosThings/Metro-for-Discord#106] opened 2019-07-31 03:41 UTC
**Describe the bug**
Profile icon at the bottom left in the guilds list is off-centered. 

**Screenshots**
![image](https://user-images.githubusercontent.com/36117192/62182105-0cb22080-b31b-11e9-8069-1513742ea56f.png)

**Comment by TakosThings** [comment] 2019-07-31 04:47
Marking as duplicate of #105

**Closed by TakosThings** 2019-07-31 04:47 UTC
Labels: Duplicate
