### ISSUE TITLE
Better disocrd porblem

### ISSUE THREAD

**Issue by andrew071117** [TakosThings/Metro-for-Discord#214] opened 2021-03-26 06:42 UTC
i have a problem with the theme on better discord look
![image](https://user-images.githubusercontent.com/81406482/112592795-ec32b600-8ddc-11eb-96ef-e1602f0d524d.png)

**Comment by TakosThings** [comment] 2021-03-26 10:25
Duplicate of #213

**Closed by TakosThings** 2021-03-26 10:25 UTC
Labels: duplicate
