### ISSUE TITLE
The usual profile overview bug

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Metro-for-Discord#110] opened 2019-08-14 06:40 UTC
Happened today to me.

![image](https://user-images.githubusercontent.com/35561383/62999581-1c903f80-be99-11e9-85e0-8aae25ce372b.png)

Self explanatory.

**Comment by TakosThings** [comment] 2019-08-14 07:15
Closing - cannot reproduce, duplicate of #93 and #104

**Closed by TakosThings** 2019-08-14 07:15 UTC
