### ISSUE TITLE
Clicking name in chat opens profile in middle of screen

### ISSUE THREAD

**Issue by silent** [TakosThings/Metro-for-Discord#91] opened 2019-06-10 06:46 UTC
**Describe the bug**
When clicking on a users name in the chat it opens in the middle of the screen

**Screenshots**
![image](https://user-images.githubusercontent.com/36117192/59177287-3de35100-8b21-11e9-9754-3603f1efc0bb.png)

**Comment by TakosThings** [comment] 2019-06-15 03:02
Closing, cannot reproduce

**Closed by TakosThings** 2019-06-15 03:02 UTC
Labels: Bug

**Comment by silent** [comment] 2019-06-15 04:06
Figured out how to reproduce. Ctrl+F in a server, look for someone's post, jump to it, click on their profile it'll open up on the middle of the screen. Now exit out of search screen on the right side and click on anyone's name in the chat. It'll continue to open in the middle until you switch to another then back to the one you were on.
