### ISSUE TITLE
Misaligned "Slowmode is enabled." indicator?

### ISSUE THREAD

**Issue by second2050** [TakosThings/Metro-for-Discord#100] opened 2019-07-12 23:33 UTC
The "Slowmode is enabled." indicator seems to be too far to the left than it should.

![image](https://user-images.githubusercontent.com/37344371/61163125-8a4cf280-a50c-11e9-9443-e39ab538aa3b.png)

**Comment by silent** [comment] 2019-07-13 03:45
![image](https://user-images.githubusercontent.com/36117192/61166654-af366b00-a4f6-11e9-9298-4a105f528ec2.png)
Hmm, I don't got that issue.

**Comment by silent** [comment] 2019-07-13 03:45
Strange, I don't got this issue: 
![image](https://user-images.githubusercontent.com/36117192/61166661-c4ab9500-a4f6-11e9-89f8-2c2ae292a8fc.png)

**Comment by TakosThings** [comment] 2019-07-13 04:24
Also don't appear to be having this issue.

I'll keep this open for a week to see if there's any updates that might cause this.

**Comment by second2050** [comment] 2019-07-16 22:30
Nothing changed since I posted it (Thought that maybe it will "fix" itself after a Discord update).
![image](https://user-images.githubusercontent.com/37344371/61334119-6b5ea100-a829-11e9-9e77-20c5b23a9768.png)

Could you tell me where in the CSS file (for BetterDiscord) the section for the slowmode indicator is?
I would like to try and fix it for myself.

**Comment by TakosThings** [comment] 2019-08-09 04:35
Closing - Cannot reproduce

**Closed by TakosThings** 2019-08-09 04:35 UTC
Labels: Bug
